In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()


In [2]:
print('Ключі iris dataset: \n{}'.format(iris_dataset.keys()))

Ключі iris dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [4]:
print('Назви відповідей: {}'.format(iris_dataset['target_names']))

Назви відповідей: ['setosa' 'versicolor' 'virginica']


In [5]:
print("Назва ознак: \n{}".format(iris_dataset['feature_names']))

Назва ознак: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print("Тип масиву data: {}".format(type(iris_dataset['data'])))

Тип масиву data: <class 'numpy.ndarray'>


In [7]:
print('Форма масиву data: {}'.format(iris_dataset['data'].shape))

Форма масиву data: (150, 4)


In [8]:
print("Значення ознак для перших п'яти прикладів:\n{}".format(iris_dataset['data'][:5]))


Значення ознак для перших п'яти прикладів:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [9]:
print("Тип масиву target: {}".format(type(iris_dataset['target'])))



Тип масиву target: <class 'numpy.ndarray'>


In [10]:
print("Відповіді:\n{}".format(iris_dataset['target']))


Відповіді:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
